name: Deploy to droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest
    environment: PRIVATE_SSH_KEY

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: 168.144.25.120
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: ./deploy.sh
          debug: true